{% set name = "pygwalker" %}
{% set version = "0.3.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: a171447f1d154cd04887e22cf5f2d656f68aaf49c6bc9c3cb57fcd53888ac61b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 1

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=3.6,<4.0
    - ipython
    - jinja2
    - pandas
    - typing_extensions
    - astor
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb ==0.9.2
    - pyarrow
    - sqlglot >=19.0.0
    - requests
    - arrow
    - sqlalchemy
    - analytics-python ==2.2.2
    - appdirs
    - pytz
    - kanaries-track ==0.0.3
    - altair >=5.0.0

test:
  imports:
    - pygwalker
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
