{% set name = "pygwalker" %}
{% set version = "0.4.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: 747b726e8acd35f20aef8ee74652a948575fb70b5fa8f816a692c9870d0ab0cb

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python
    - jinja2
    - ipython
    - astor
    - typing_extensions
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb >=0.10.1,<2.0.0
    - pyarrow
    - sqlglot >=23.15.8
    - requests
    - arrow
    - sqlalchemy
    - gw-dsl-parser ==0.1.49.1
    - appdirs
    - segment-analytics-python ==2.2.3
    - pandas
    - pytz
    - kanaries-track ==0.0.5
    - cachetools
    - packaging
    - numpy
    - ipylab <=1.0.0
    - python-quickjs  # [not win]
    - traitlets
    - anywidget

test:
  imports:
    - pygwalker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://kanaries.net/pygwalker
  summary: Combining Jupyter Notebook with a Tableau-like UI
  description: PyGWalker can simplify your Jupyter Notebook data analysis and data visualization workflow, by turning your pandas dataframe into an interactive user interface for visual exploration.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://kanaries.net/pygwalker
  dev_url: https://github.com/Kanaries/pygwalker

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
