{% set name = "pygwalker" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: e25fa8467f2e6865f67ee5bbb26f8b9d06accc9dbcdfb4ee5bebf9551042718a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=3.6,<4.0
    - ipython
    - jinja2
    - pandas
    - typing_extensions
    - astor
    - ipywidgets
    - pydantic
    - psutil
    - duckdb

test:
  imports:
    - pygwalker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
