{% set name = "pygwalker" %}
{% set version = "0.1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: befae03ed94ac40c66ab87283c8d4ee567598d444c0ea375c3dd8dccb686f65a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.6,<4.0
    - ipython
    - jinja2
    - pandas

test:
  imports:
    - pygwalker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
 
